# .github/workflows/build-apk.yml
name: Build Flet APK

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 11076708
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet
        pip install -r requirements.txt
        
    - name: Build APK
      run: |
        flet pack main.py --platform android \
          --name "URL Shortener" \
          --description "Mobile URL Shortener App" \
          --author "Giovanni" \
          --version "1.0.0" \
          --build-number 1 \
          --icon icon.png \
          --distpath dist
          
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: url-shortener-apk
        path: dist/*.apk
        
    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
